server:
 port: ${PORT:0}

spring:
 application:
  name: hr-payroll
 
hr-worker:
 host: http://localhost:8001/workers/{id}
 ribbon:
  listOfServers: localhost:8001, localhost:8002
  
  
eureka:
 client:
  service-url:
   defaultZone: http://hr-eureka-server:8761/eureka 
 instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

## MESMO TEMPO CONFIG TIMEOUT NO ZUUL, PRECISAMOS COLOCAR AQUI TBM, POIS O RIBBON DEFAULT É 1S   
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 60000
      
ribbon:
 ConnectionTimeout: 10000
 ReadTimeout: 20000
  