server:
 port: 8101

spring:
 application:
  name: hr-payroll

host:
 hr-worker: http://localhost:8001/workers/{id}
 
 
hr-worker:
 host: http://localhost:8001/workers/{id}
 ribbon:
  listOfServers: localhost:8001, localhost:8002