server:
  #port: 8001
  port: 8765
  
eureka:
 client:
  service-url:
   defaultZone: http://hr-eureka-server:8761/eureka 

spring:
  application:
    name: hr-api-gateway-zuul


zuul:
  routes:
    worker:
     service-id: hr-worker
     path: /hr-worker/**
    payroll:
     service-id: hr-payroll
     path: /hr-payroll/**
    user:
     service-id: hr-user
     path: /hr-user/**
    oauth:
     service-id: hr-oauth
     path: /hr-oauth/**
     sensitive-headers: Cookie, Set-Cookie

## CONTROLE DE TIMEOUT IMPORTANTISSIMO *default é 1s
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 60000
      
ribbon:
 ConnectionTimeout: 10000
 ReadTimeout: 20000
     